TImeTable_Generator/Models/BatchRoutine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TImeTable_Generator.Models
{
    public class BatchRoutine
    {
    }
}

TImeTable_Generator/Models/LoginRoutine.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TImeTable_Generator.Models
{
    public class LoginRoutine
    {
    }
}

TImeTable_Generator/Controllers/BatchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TImeTable_Generator.Controllers
{
    public class BatchController : Controller
    {
        // GET: Batch
        public ActionResult Index()
        {
            return View();
        }

        // GET: Batch/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Batch/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Batch/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Batch/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Batch/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Batch/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Batch/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TImeTable_Generator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TImeTable_Generator.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        // GET: Home/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Home/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Home/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Home/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Home/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TImeTable_Generator/Controllers/Login_SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TImeTable_Generator.Controllers
{
    public class Login_SignUpController : Controller
    {
        // GET: Login_SignUp
        public ActionResult Index()
        {
            return View();
        }

        // GET: Login_SignUp/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Login_SignUp/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Login_SignUp/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Login_SignUp/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Login_SignUp/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Login_SignUp/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Login_SignUp/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TImeTable_Generator/Views/Batch/Index.cshtml
@model TImeTable_Generator.Models.BatchRoutine

@{
    ViewBag.Title = "Index";
}




<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Batch</title>
    @*<link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@

    @*<link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" />*@
    <link href="@Url.Content("~/Content/Input-Design/css/Style.css")" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="shade">
        <div class="blackboard">
            <div class="form">
                <p>
                    <label>Name: </label>
                    <input type="text" />
                </p>
                <p>
                    <label>Email: </label>
                    <input type="text" />
                </p>
                <p>
                    <label>Phone: </label>
                    <input type="tel" />
                </p>
                <p>
                    <label>Subject: </label>
                    <input type="text" />
                </p>
                <p>
                    <label>Message: </label>
                    <textarea></textarea>
                </p>
                <p class="wipeout">
                    <input type="submit" value="Send" />
                </p>
            </div>
        </div>
    </div>

</body>

TImeTable_Generator/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

TImeTable_Generator/Views/Login_SignUp/Index.cshtml
@model TImeTable_Generator.Models.LoginRoutine

@{
    ViewBag.Title = "Index";
}

@*<h2>Index</h2>*@


<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <link type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
    <link href="@Url.Content("~/Content/Login_SignUp/css/Style.css")" rel="stylesheet" type="text/css" />
   

</head>
<body>
    @*<h2>Login Form</h2>*@
    @*<h2>Weekly Coding Challenge #1: Sign in/up Form</h2>*@
    <div class="container" id="container">
        <div class="form-container sign-up-container">
            @using (Html.BeginForm("SignUp", "Login_SignUp", FormMethod.Post))
            {
                <h1>Create Account</h1>
                @*<div class="social-container">
            <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
            <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
            <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
            </div>*@
                @*<span>or use your email for registration</span>*@
                @*<input type="text" placeholder="Name" />*@
                @Html.TextBox("s_Name", "", new { placeholder = "Name" })
                @*<input type="email" placeholder="Email" />*@
                @Html.TextBox("s_Email", "", new { placeholder = "Email", type = "email" })
                @*<input type="password" placeholder="Password" />*@
                @Html.TextBox("s_Password", "", new { placeholder = "Password", type = "password" })
                @*<button>Sign Up</button>*@
                <input type="submit" value="Sign Up" style="border-radius: 20px;
                                                        border: 1px solid #FF4B2B;
                                                        background-color: #FF4B2B;
                                                        color: #FFFFFF;
                                                        font-size: 12px;
                                                        font-weight: bold;
                                                        padding: 12px 45px;
                                                        letter-spacing: 1px;
                                                        text-transform: uppercase;
                                                        transition: transform 80ms ease-in;"/>
            }
        </div>
        <div class="form-container sign-in-container">
            @using (Html.BeginForm("SignUp", "Login_SignUp", FormMethod.Post))
            {
                <h1>Sign in</h1>
                @*<div class="social-container">
                <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
                <a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
            </div>
            <span>or use your account</span>*@
                @*<input type="email" placeholder="Email" />
            <input type="password" placeholder="Password" />*@
                @Html.TextBox("l_Name", "", new { placeholder = "Name" })
                @Html.TextBox("l_Password", "", new { placeholder = "Password", type = "password" })
                <a href="#">Forgot your password?</a>
                @*<button>Sign In</button>*@
                <input type="submit" value="Login" style="border-radius: 20px;
                                                        border: 1px solid #FF4B2B;
                                                        background-color: #FF4B2B;
                                                        color: #FFFFFF;
                                                        font-size: 12px;
                                                        font-weight: bold;
                                                        padding: 12px 45px;
                                                        letter-spacing: 1px;
                                                        text-transform: uppercase;
                                                        transition: transform 80ms ease-in;" />
            }
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>Welcome Back!</h1>
                    <p>To keep connected with us please login with your personal info</p>
                    <button class="ghost" id="signIn">Sign In</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>New User?</h1>
                    <p>Sign Up with us to get started with Time Table Generator</p>
                    <button class="ghost" id="signUp">Sign Up</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="@Url.Content("~/Content/Login_SignUp/js/app.js")"></script>
</body>
</html>

TImeTable_Generator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    @*<script src="~/Scripts/modernizr-2.6.2.js"></script>*@
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>*@

    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>